language: java

<<<<<<< HEAD
jdk:
  - oraclejdk8

=======
>>>>>>> travis 3 try yml
sudo: false


before_install:
  - wget http://apache.claz.org/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
  - tar zxvf apache-maven-3.3.9-bin.tar.gz
  - chmod +x apache-maven-3.3.9/bin/mvn
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$PWD/apache-maven-3.3.9/bin:${PATH}
  - hash -r


cache:
  directories:
    - $HOME/.m2


notifications:
  email:
  - torrespp@gmail.com
